# permissions for end users to view proxyconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: proxyconfig-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: proxy-config-operator
    app.kubernetes.io/part-of: proxy-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: proxyconfig-viewer-role
rules:
- apiGroups:
  - proxy.k8s.kemo.dev
  resources:
  - proxyconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.k8s.kemo.dev
  resources:
  - proxyconfigs/status
  verbs:
  - get
